version: '3'
services:
  server:
    build: ./server
    ports:
      - "80:80"
    restart: always

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: always
