version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://ghost:ghostishere@cluster0.llqvm.mongodb.net/
