version: "3.8"
services:
  app:
    container_name: fullstack-app
    build: .
    ports:
      - "80:80"      # Map Express server to port 80
      - "5173:5173"  # Map Vite frontend to default port
    environment:
      - NODE_ENV=production
    restart: always
